# Generated by Django 4.1 on 2023-05-16 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('nama_brand', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=50)),
                ('cp_name', models.CharField(max_length=50)),
                ('cp_email', models.CharField(max_length=50)),
            ],
        ),
    ]
