# Generated by Django 4.1 on 2023-05-17 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sponsor',
        ),
    ]
